#Q.) input -> condition (math query or general query) -> llm1 (math model) or llm2 (general model) -> output
# Implement a conditional chain that takes an input query, determines whether it is a math query or a general query, and then routes it to the appropriate LLM (math model for math queries and general model for general queries) to generate the output.

from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnableLambda
from dotenv import load_dotenv

# Load environment variables from a .env file
load_dotenv()

# Prompt for math queries
prompt1 = PromptTemplate(
    template='You are an expert math assistant.Solve the math query: {math_query}',
    input_variables=['math_query']
)

# Prompt for general queries
prompt2 = PromptTemplate(
    template='You are a helpful assistant.Answer the general query: {general_query}',   
    input_variables=['general_query']
)

# model
llm = ChatGroq(model="llama-3.1-8b-instant", temperature=0.4)

# Parser 
parser = StrOutputParser()

# Chains for math and general queries
math_chain = prompt1 | llm | parser
general_chain = prompt2 | llm | parser

# Branching logic to determine whether the input query is a math query or a general query. This is done using a RunnableLambda, which allows us to define a custom function that checks the input and routes it to the appropriate chain based on the presence of certain keywords (in this case, "math"). The function checks if the word "math" is present in the input query (case-insensitive) and returns "math_query" if it is, or "general_query" if it is not.
branch = RunnableLambda(
    lambda x: "math_query" if "math" in x["input"].lower() else "general_query"
)

# Final chain that takes the input query, applies the branching logic to determine which chain to route it to, and then generates the output using the appropriate LLM based on whether it's a math query or a general query. The branch function will route the input to either the math_chain or the general_chain based on the presence of the "math" keyword.
result = branch.invoke({"input": "The math problem is: What is the integral of x^2?"})
result2 = branch.invoke({"input": "What is the capital of France?"})

# Print the final result, which will be the output generated by either the math_chain or the general_chain based on the input query.
print(result)
print(result2)
