# Runnable Primitives in Langchain
# Runnable primitives are the basic building blocks of Runnables in Langchain. They represent individual operations or tasks that can be executed as part of a Runnable workflow. These primitives can be simple functions, methods, or even more complex operations that you define.

# 1.) RunnableSequence: This primitive allows you to execute a sequence of Runnables in a specific order. Each Runnable in the sequence will be executed one after the other, and the output of one Runnable can be passed as input to the next.

from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.runnables import RunnableSequence
from dotenv import load_dotenv
from langchain_core.output_parsers import StrOutputParser

# Load environment variables from .env file
load_dotenv()

# Model initialization
model = ChatGroq(model="llama-3.1-8b-instant", temperature=0.4)

# Prompt initialization
prompt = PromptTemplate(
    template='Write  a joke about {topic}',
    input_variables=['topic']
)

# Output parser initialization
parser = StrOutputParser()

# Create a RunnableSequence that combines the prompt, model, and parser. The order of execution will be: first the prompt will generate the input for the model, then the model will generate a response based on the prompt, and finally, the parser will process the model's output to produce the final result.
chain = RunnableSequence(
    prompt ,
    model,
    parser
)

# Now we can invoke the chain with a specific topic to generate a joke about that topic. The `invoke` method will execute the sequence of operations defined in the `RunnableSequence` and return the final result.
result = chain.invoke({'topic': 'Rahul Gandhi'})

# Finally, we print the result, which should be a joke about Rahul Gandhi generated by the model based on the prompt we provided.

print(result)